// Text content for the minigames. Add lines freely — games pick unused ones first.

export const MOST_LIKELY = [
  'falde i søvn til festen',
  'sende en besked til sin eks i aften',
  'blive gift først',
  'synge karaoke uden at blive spurgt',
  'ende med at danse på bordet',
  'miste sin telefon i aften',
  'blive kendt',
  'starte en diskussion om politik kl. 3 om natten',
  'spise kebab på vej hjem',
  'være den sidste, der går hjem',
  'have de værste tømmermænd i morgen',
  'ringe til sin mor i løbet af aftenen',
  'vinde i Lotto og bruge det hele på en uge',
  'overleve en zombieapokalypse',
  'blive millionær',
  'flytte til udlandet',
  'holde fest på en tirsdag',
  'græde til en film',
  'snyde i et brætspil',
  'komme for sent til sit eget bryllup',
  'tage et billede af sin mad',
  'glemme navnet på en, de lige har mødt',
  'fare vild på vej hjem',
  'ende i en viral TikTok-video',
  'tro på spøgelser',
  'adoptere fem katte',
  'snakke i søvne',
  'blive sur over et spil kort',
  'vinde en dansekonkurrence',
  'bruge en hel løn på tøj',
  'overleve en uge alene i skoven',
  'sige "bare én til" og mene det modsatte',
  'skrive en bestseller',
  'bestille pizza kl. 4 om natten',
  'give en tale, som ingen har bedt om',
  'starte en polonaise',
  'blive bedste venner med en fremmed på toilettet',
  'glemme, hvor de har parkeret',
  'tage en powernap midt i festen',
  'have en hemmelig dagbog',
  'blive stoppet af politiet for at gå for hurtigt',
  'sende et billede til den forkerte gruppechat',
  'tage på en spontan weekendtur i morgen',
  'svare "nej, jeg er frisk!" og gå hjem fem minutter senere',
  'få et nyt kælenavn i aften',
];

export const NEVER_HAVE = [
  'sovet over mig til en vigtig aftale',
  'sendt en sms til den forkerte person',
  'løjet om min alder',
  'spist noget, der lå på gulvet',
  'grædt til en Disney-film',
  'været til koncert alene',
  'faldet i søvn i biografen',
  'stalket min eks på sociale medier',
  'snydt i et spil',
  'sunget højt i bad',
  'glemt en vens fødselsdag',
  'kørt i den samme forlystelse fem gange i træk',
  'haft en imaginær ven',
  'sagt "jeg elsker dig" først',
  'fået en p-bøde',
  'lavet en dansevideo',
  'været på blind date',
  'kysset nogen til en julefrokost',
  'brækket en knogle',
  'været på tv',
  'mistet min telefon i byen',
  'spist en hel pizza alene',
  'ghostet nogen',
  'vundet en konkurrence',
  'lavet mad, der gav nogen ondt i maven',
  'sagt op fra et job',
  'nøgenbadet',
  'haft et pinligt kælenavn',
  'googlet mig selv',
  'grinet på et helt upassende tidspunkt',
  'glemt min egen pinkode',
  'faldet på et dansegulv',
  'skrevet et kærlighedsdigt',
  'taget en selfie med en kendt person',
  'låst mig selv ude',
  'sovet i telt på en festival',
  'brugt over 1.000 kr. i byen på én aften',
  'fået en tatovering, jeg fortryder',
  'meldt mig syg for at slippe for noget',
  'været forelsket i en lærer',
  'haft en hemmelig profil på sociale medier',
  'lavet en prank, der gik helt galt',
  'sagt noget pinligt til en chef',
  'gået i pyjamas en hel dag',
  'tabt min telefon i toilettet',
  'spist morgenmad klokken 15',
  'sms\'et nogen kl. 3 om natten og fortrudt det',
  'været til en fest, hvor jeg ikke kendte nogen',
  'lagt et billede op og slettet det igen efter fem minutter',
  'taget en taxa under 1 km',
];

export const RULES = [
  'Ingen må sige ordet "drik" — siger du det, tager du 2 slurke.',
  'Du må kun drikke med venstre hånd. Snyder du, er det 1 slurk.',
  'Ingen fornavne! Siger du et fornavn, drikker du 1 slurk.',
  'Den, der griner højest, drikker 1 slurk.',
  'Skål kun med øjenkontakt — ellers 1 slurk.',
  'Ingen må pege. Peger du, drikker du.',
  'Sig "skål" på et andet sprog, før du drikker.',
  'Ingen må sige "ja" eller "nej".',
  'Alle taler med en accent efter eget valg.',
  'Ingen bandeord — bander du, drikker du.',
  'Hver gang sangen skifter, tager alle 1 slurk.',
  'Rejs dig op, før du drikker.',
  'Alle sætninger skal slutte med "… i bukserne".',
  'Kald alle "kaptajn". Glemmer du det, er det 1 slurk.',
  'Drik med lillefingeren strakt ud.',
  'Ingen må sige "øl" — det hedder "guldsaft" nu.',
  'Når nogen råber "SKÅL", svarer alle "HEJ!" — den sidste drikker.',
  'Ingen må krydse benene.',
  'Du må kun tale om dig selv i tredje person.',
  'Den, der tjekker sin telefon (uden for SKÅL), drikker 1 slurk.',
  'Sig tak til alt — glemmer du det, er det 1 slurk.',
  'Alle skal klinke med mindst to personer, før de drikker.',
  'Rører værten sin næse, gør alle det samme — den sidste drikker 2.',
  'Ingen må sige "jeg" — så er det 1 slurk.',
  'Hver gang nogen siger "faktisk", drikker de 1 slurk.',
];

export const TRUTHS = [
  'Hvad er det mest pinlige, der er sket for dig i byen?',
  'Hvem i rummet ville du helst bytte liv med i en dag?',
  'Hvad er den værste date, du har været på?',
  'Hvad er din mest irrationelle frygt?',
  'Hvilken sang kan du alle ordene til, men ville aldrig indrømme det?',
  'Hvad er det dummeste, du har brugt penge på?',
  'Hvad er din værste vane?',
  'Hvem var dit første crush?',
  'Hvad er den største løgn, du har fortalt dine forældre?',
  'Hvad ville du gøre, hvis du var usynlig i en dag?',
  'Hvilken kendis har du et hemmeligt crush på?',
  'Hvad er det mærkeligste, du nogensinde har spist?',
  'Hvad er dit mest pinlige barndomsminde?',
  'Hvad er den værste sms, du har sendt?',
  'Hvad er det første, du ville købe, hvis du vandt en million?',
  'Hvad er dit guilty pleasure-tv-program?',
  'Hvad er det værste råd, du nogensinde har fulgt?',
  'Hvad er det mest spontane, du nogensinde har gjort?',
  'Hvad er din yndlingsting ved personen til venstre for dig?',
  'Hvornår grinede du sidst, til du græd?',
  'Hvad ville du være, da du var lille?',
  'Hvad er den mærkeligste besked i din telefon lige nu?',
  'Hvilket talent ville du ønske, du havde?',
  'Hvad er det mest pinlige i din søgehistorik?',
  'Hvad er den dårligste scorereplik, du har brugt?',
  'Hvem i rummet ville overleve længst på en øde ø — og hvorfor ikke dig?',
  'Hvad er en ting, ingen her ved om dig?',
  'Hvad er din mest upopulære holdning?',
  'Hvad er det mest barnlige, du stadig gør?',
  'Hvis du skulle slette én app for altid, hvilken ville det være?',
];

export const DARES = [
  'Lav din bedste dyrelyd, til nogen gætter dyret.',
  'Tal med fransk accent de næste 3 minutter.',
  'Lav 10 armbøjninger — nu!',
  'Syng omkvædet af en sang, gruppen vælger.',
  'Hold en dramatisk skåltale på 30 sekunder.',
  'Dans uden musik i 20 sekunder.',
  'Imitér en i rummet — de andre skal gætte hvem.',
  'Gå baglæns de næste 5 minutter.',
  'Fortæl en vittighed. Griner ingen, drikker du 2 slurke.',
  'Gå catwalk gennem rummet.',
  'Byt jakke, kasket eller trøje med personen til venstre.',
  'Lav en robotdans i 15 sekunder.',
  'Sig alfabetet baglæns så langt, du kan.',
  'Giv personen over for dig et kompliment på rim.',
  'Hold en planke i 30 sekunder.',
  'Lav en reklame for den drik, du holder i hånden.',
  'Vær sportskommentator på det, der sker i rummet, i 1 minut.',
  'Lav din bedste imitation af en kendt dansker.',
  'Syng "I dag er det Sørens fødselsdag" som en operasanger.',
  'Stå på ét ben i 1 minut.',
  'Lad gruppen vælge din næste drink.',
  'Fortæl en pinlig historie med nyhedsoplæserstemme.',
  'Vis dit bedste dansemove.',
  'Giv en high five til alle i rummet.',
  'Skriv et digt på fire linjer om din drink — og læs det højt.',
  'Tal kun i spørgsmål de næste 3 minutter.',
  'Lav 15 squats og råb "SKÅL" ved hver.',
  'Lav en luftguitar-solo i 20 sekunder.',
  'Fortæl gruppen, hvad du virkelig synes om deres musiksmag.',
  'Lav en TV-reklame for festens vært.',
];

export const CATEGORIES = [
  'Ølmærker',
  'Ting i et køleskab',
  'Danske byer',
  'Fodboldklubber',
  'Kendte danskere',
  'Drinks og cocktails',
  'Ting, der er gule',
  'Bilmærker',
  'Dyr i Afrika',
  'Pizzatoppings',
  'Disney-film',
  'Sportsgrene',
  'Lande i Europa',
  'Ting på et badeværelse',
  'Slik og chokolade',
  'Superhelte',
  'Musikinstrumenter',
  'Brætspil',
  'Tv-serier',
  'Frugter',
  'Grøntsager',
  'Ting, der kan flyve',
  'Danske sangere og bands',
  'Ting, man tager med på festival',
  'Hovedstæder',
  'Tøjmærker',
  'Ting, der er runde',
  'Spiritusmærker',
  'Juleting',
  'Hunderacer',
  'Computerspil',
  'Apps på telefonen',
  'Ting i en skoletaske',
  'Fastfood-kæder',
  'Sodavandsmærker',
  'Danske retter',
  'Ting, der er røde',
  'Ord, der rimer på "fest"',
  'Kendte film',
  'Ting, man siger til en fest',
];

export const TOASTS = [
  'aftenens MVP',
  'den bedste latter',
  'at holde festen kørende',
  'det flotteste outfit',
  'at være præcis den, de er',
  'de bedste dansemoves',
  'at have taget sig tid i aften',
  'den bedste energi',
  'aftenens bedste historie',
  'at være en legende',
];
