// Quiz questions. `a` lists the options with the correct one FIRST — the game shuffles them.

export const QUIZ = [
  { q: 'Hvilket land kommer Jägermeister fra?', a: ['Tyskland', 'Østrig', 'Schweiz', 'Danmark'] },
  { q: 'Hvor mange gram ren alkohol er der i én genstand i Danmark?', a: ['12 gram', '8 gram', '10 gram', '15 gram'] },
  { q: 'I hvilken by blev Carlsberg grundlagt?', a: ['København', 'Odense', 'Aarhus', 'Fredericia'] },
  { q: 'Hvilken spiritus er grundlaget i en Mojito?', a: ['Rom', 'Vodka', 'Gin', 'Tequila'] },
  { q: 'Hvad laves cider traditionelt af?', a: ['Æbler', 'Pærer', 'Druer', 'Blommer'] },
  { q: 'Hvilket land kommer tequila fra?', a: ['Mexico', 'Spanien', 'Cuba', 'Peru'] },
  { q: 'Hvilket bær giver gin sin karakteristiske smag?', a: ['Enebær', 'Tranebær', 'Hindbær', 'Solbær'] },
  { q: 'Hvad blev kåret som Danmarks nationalret i 2014?', a: ['Stegt flæsk med persillesovs', 'Frikadeller', 'Æbleskiver', 'Smørrebrød'] },
  { q: 'Hvor mange regioner er Danmark inddelt i?', a: ['5', '4', '6', '14'] },
  { q: 'Hvilket år blev Danmark medlem af EF (nu EU)?', a: ['1973', '1972', '1986', '1992'] },
  { q: 'Hvad er hovedstaden i Australien?', a: ['Canberra', 'Sydney', 'Melbourne', 'Perth'] },
  { q: 'Hvor mange ben har en edderkop?', a: ['8', '6', '10', '12'] },
  { q: 'Hvilken planet er den største i solsystemet?', a: ['Jupiter', 'Saturn', 'Neptun', 'Uranus'] },
  { q: 'Hvem malede Mona Lisa?', a: ['Leonardo da Vinci', 'Michelangelo', 'Rafael', 'Rembrandt'] },
  { q: 'Hvilket grundstof har det kemiske symbol O?', a: ['Ilt', 'Guld', 'Osmium', 'Brint'] },
  { q: 'Hvor mange spillere har et fodboldhold på banen ad gangen?', a: ['11', '10', '9', '12'] },
  { q: 'Hvilket land vandt EM i fodbold for herrer i 1992?', a: ['Danmark', 'Tyskland', 'Holland', 'Sverige'] },
  { q: 'Hvad hedder H.C. Andersens eventyr om en fugl, der vokser op og bliver en smuk svane?', a: ['Den grimme ælling', 'Den lille havfrue', 'Fyrtøjet', 'Nattergalen'] },
  { q: 'Hvor mange minutter er der i et døgn?', a: ['1.440', '1.240', '1.640', '2.400'] },
  { q: 'Hvad er verdens største dyr?', a: ['Blåhvalen', 'Afrikansk elefant', 'Kaskelotten', 'Hvalhajen'] },
  { q: 'Hvilket land har flest indbyggere i verden?', a: ['Indien', 'Kina', 'USA', 'Indonesien'] },
  { q: 'Hvad er hovedstaden i Canada?', a: ['Ottawa', 'Toronto', 'Vancouver', 'Montreal'] },
  { q: 'Hvilken by bliver kaldt "Smilets By"?', a: ['Aarhus', 'Odense', 'Aalborg', 'Vejle'] },
  { q: 'Hvor mange strenge har en almindelig guitar?', a: ['6', '4', '5', '8'] },
  { q: 'Hvad blander man vodka med i en klassisk Screwdriver?', a: ['Appelsinjuice', 'Tranebærjuice', 'Tonic', 'Cola'] },
  { q: 'Hvad er der i en Cuba Libre ud over rom og lime?', a: ['Cola', 'Sprite', 'Tonic', 'Ginger ale'] },
  { q: 'Hvilken farve får man, når man blander blå og gul?', a: ['Grøn', 'Lilla', 'Orange', 'Brun'] },
  { q: 'Hvor mange hjerter har en blæksprutte?', a: ['3', '1', '2', '8'] },
  { q: 'Hvilket instrument spiller danske Lars Ulrich i Metallica?', a: ['Trommer', 'Guitar', 'Bas', 'Keyboard'] },
  { q: 'Hvilket år tog LEGO patent på den klassiske LEGO-klods?', a: ['1958', '1932', '1968', '1949'] },
  { q: 'Hvad hedder Danmarks længste vandløb?', a: ['Gudenåen', 'Skjern Å', 'Storå', 'Suså'] },
  { q: 'Hvilket land kommer drinken Caipirinha fra?', a: ['Brasilien', 'Mexico', 'Cuba', 'Argentina'] },
  { q: 'Hvilken spiritus er der i en klassisk Irish Coffee?', a: ['Whiskey', 'Rom', 'Vodka', 'Gin'] },
  { q: 'Ved hvilken temperatur koger vand ved havoverfladen?', a: ['100 °C', '90 °C', '110 °C', '120 °C'] },
  { q: 'Hvilket år faldt Berlinmuren?', a: ['1989', '1991', '1987', '1990'] },
  { q: 'Hvem skrev "Romeo og Julie"?', a: ['William Shakespeare', 'Charles Dickens', 'Ludvig Holberg', 'Goethe'] },
  { q: 'Hvem blev Danmarks konge i januar 2024?', a: ['Frederik 10.', 'Christian 10.', 'Frederik 9.', 'Christian 11.'] },
  { q: 'Hvilken gas udgør størstedelen af luften, vi indånder?', a: ['Kvælstof', 'Ilt', 'CO₂', 'Argon'] },
  { q: 'Hvor mange kort er der i et almindeligt spil kort uden jokere?', a: ['52', '48', '54', '56'] },
  { q: 'Hvad er hovedingrediensen i guacamole?', a: ['Avocado', 'Ærter', 'Agurk', 'Squash'] },
  { q: 'Hvilken ølstil er Guinness mest kendt for?', a: ['Stout', 'Pilsner', 'IPA', 'Hvedeøl'] },
  { q: 'Hvilken slags drik er Gammel Dansk?', a: ['En bitter', 'En rødvin', 'En øl', 'En cider'] },
  { q: 'Hvor mange procent alkohol har en almindelig dansk pilsner typisk?', a: ['Ca. 4,6 %', 'Ca. 2 %', 'Ca. 8 %', 'Ca. 12 %'] },
  { q: 'Hvilken energidrik er klassisk i en Jägerbomb?', a: ['Red Bull', 'Faxe Kondi', 'Cola', 'Tonic'] },
  { q: 'Hvilket land kommer pizzaen oprindeligt fra?', a: ['Italien', 'Grækenland', 'USA', 'Spanien'] },
  { q: 'Hvem skrev eventyret "Den lille havfrue"?', a: ['H.C. Andersen', 'Karen Blixen', 'Søren Kierkegaard', 'Ludvig Holberg'] },
];
